### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/core@5.0.3

### ISSUE THREAD

**Issue by tss-kcirtap** [zyra/ionic-tooltips#26]
this error keeps poppin' whenever I try to install this plugin.

```
+-- @angular/animations@4.1.3
`-- UNMET PEER DEPENDENCY @angular/core@5.0.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/animations@4.1.3 requires a peer of @angular/core@4.1.3 but none was installed.
```
ionic version: 3.19.0
npm version: 3.10.10
angular-cli: 1.0.0-beta.28.3
node: 6.11.2
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 5.0.3
@angular/compiler: 5.0.3
@angular/compiler-cli: 5.0.3
@angular/core: 5.0.3

**Comment by wvervuurt** [comment]
I had the same problem. In my case it was because I am using version 5.0.3, but the installation instructions for this module say "npm i --save --save-exact @angular/animations@4.1.3".

I have changed that version number to 5.0.3, and everything works perfectly.

I am guessing something alike was your issue. You can change the version number when you first run this command, or change it later in src/app/app.module.ts. I am only doing this because it works, I'm not sure if it is supported (I'm new to Node and Angular development). If this is indeed right, we should change the installation instructions in the readme.

**Comment by willyboy** [comment]
@tss-kcirtap You should open a PR for the package.json to upgrade this to angular ^5.0.0
It's an easy fix that will allow you to say you're a contributor on an open source repo :)

**Comment by jayeshkorat18** [comment]
I have change version npm i --save --save-exact @angular/animations@5.03. Successfully installed 

but still got error when import-

> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
> 
> @NgModule({
>   ...
>   imports: [
>     ...
>     BrowserAnimationsModule
>   ]
> })

 
error is: 

> Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/Tejas/Jayesh/project/SDS/Firefuze/code/FirefuzeVer3/FirefuzeMobileAppVer3/node_modules/@angular/animations/@angular/animations.es5.js'

Please let me know if any solution for this
